name: streeto
description: Street to me!

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.2+1
  get_it: ^1.0.3+2
  flutter_bloc: ^0.15.1
  logging: ^0.11.3+2
  flutter_i18n: ^0.6.4
  geolocator: ^5.1.4+1
  permission_handler: '^3.1.0'
  flutter_spinkit: ^3.1.0
  chopper: ^3.0.1
  json_annotation: ^2.0.0
  transparent_image: ^1.0.0
  url_launcher: ^5.2.3
  sembast: ^2.1.0
  path_provider: ^1.3.1
  shared_preferences: ^0.5.3+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  build_runner: any
  chopper_generator: any
  json_serializable: ^3.0.0
  flutter_cache_manager: ^1.1.3
  cached_network_image: ^1.1.2+1

flutter:
  uses-material-design: true
  assets:
    - assets/locales/
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
      - asset: fonts/nunito.ttf


# Generate icons command: flutter packages pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon_ios.png"
  image_path_android: "assets/launcher/icon_android_fallback.png"
  adaptive_icon_background: "#1dd861"
  adaptive_icon_foreground: "assets/launcher/icon_android_adaptative_foreground.png"
